WITH MONTLY_REVS AS(
SELECT
    DATE_TRUNC('month', s.ORDERDATE) as ordermonth, p.PRODUCTNAME, SUM(REVENUE) AS REVENUE
FROM subscriptions s
INNER JOIN products p
ON s.PRODUCTID=p.PRODUCTID
WHERE s.ORDERDATE BETWEEN '2022-01-01' AND '2022-12-31'
GROUP BY DATE_TRUNC('month', s.ORDERDATE), p.PRODUCTNAME
ORDER BY p.PRODUCTNAME
)

SELECT
  PRODUCTNAME, 
  MIN(REVENUE) AS MIN_REV,
  MAX(REVENUE) AS MAX_REV,
  AVG(REVENUE) AS AVG_REV,
  STDDEV(REVENUE) AS STD_DEV_REV
FROM MONTLY_REVS
GROUP BY PRODUCTNAME
